[tool.black]
line-length = 130
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 130
default_section = "THIRDPARTY"
known_third_party = []
known_first_party = []
